# Generated by Django 2.2.7 on 2019-11-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='lat',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='marker',
            name='lng',
            field=models.FloatField(default=None),
        ),
    ]
